# Generated by Django 4.2.6 on 2023-10-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='price_per_unit',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='reciperequirement',
            old_name='quantity_required',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='lbs', max_length=255),
            preserve_default=False,
        ),
    ]
